server:
  port: 8864

spring:
#  application:
#    name: userService # user服务的服务名称
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      server-addr: localhost:8848 # Nacos服务端地址
#      discovery:
#        username: nacos # Nacos开启权限验证后，需要设置登录用户名
#        password: nacos # Nacos开启权限验证后，需要设置登录密码
#        namespace: f20f0bdd-8b41-41a2-96c8-6aa946f903fc # 设置服务在Nacos中所属的命名空间ID
#        group: stone1 # 设置服务在Nacos中所属的分组
#        cluster-name: BJ # 配置集群名称，也就是机房位置，例如：HZ 杭州
#        ephemeral: false # 设置为非临时实例

mybatis:
  type-aliases-package: com.djn.user.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  pattern:
    dateformat: MM-dd HH:ss:SSS
  level:
    com.djn: debug

#eureka:
#  client:
#    service-url: # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka/

pattern:
  name: 本地环境local