server:
  port: 10086 # 服务端口

# 为 Eureka自身的服务注册 而做的配置
spring:
  application:
    name: eurekaServer # Eureka的服务名称
eureka:
  client:
    serviceUrl: # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka/
    fetch-registry: false # 是否从eureka中拉取信息列表
  server:
    enable-self-preservation: true